---
title: 'splitTips'
description: 'Parse tip labels into a dataframe with multiple columns for each content'
toc: true
toc-depth: 3
---


```{r}
#| eval: false
catGenes::splitTips()
```

### Description

This function is designed to split tip labels into a dataframe
object. Each column in the dataframe corresponds to the genus, species,
infraspecific name, and associated voucher and GenBank information, whenever
available. If doubtful particles such as 'aff.' or 'cf.' are provided, they
will also be separated into a distinct column. When an infraspecific rank
marker ('var.' or 'subsp.') is present, the epithet that follows it (not
the marker itself) is captured as the infraspecific name. Tip labels can be
supplied directly as a vector, or read from a NEXUS, FASTA or PHYLIP
alignment file.

### Arguments

| Argument | Description |
|---|---|
| tiplabels | A vector of tip labels from a phylogeny. Either `tiplabels` or `file` must be provided. |
| file | Path to a NEXUS, FASTA or PHYLIP alignment file, from which the taxon/tip labels will be extracted. Only used when `tiplabels = NULL`. |

### Value

A dataframe.

### Examples

```r
library(catGenes)

data(Harpalyce_bayes_tree)

df <- splitTips(tiplabels = Harpalyce_bayes_tree@phylo$tip.label)

df <- splitTips(file = "myalignment.nex")
```


