---
title: "Install"
format:
  html:
    toc: true
---

<style>
  body {
    background-repeat: repeat-y;
    background-size: cover;
    background-attachment: fixed;
    background-position: top center;
    position: relative;
    z-index: 0;
  }

  .background-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(255, 255, 255, 0.8); /* white with 80% opacity */
    z-index: -1;
  }
</style>

## Install the package

You can install the latest development version of `catGenes` package from [GitHub](https://github.com/DBOSlab/catGenes) as follows:


```{r, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE)) 
install.packages("BiocManager") 

# Install the development version of catGenes from GitHub, 
# together with its required dependencies 
BiocManager::install("DBOSlab/catGenes", dependencies = TRUE)
```

:::{.callout-note}
`catGenes` is currently distributed from GitHub. Make sure BiocManager is installed before running BiocManager::install().

:::{.callout-caution}
Some functions in `catGenes` rely on additional external software or online resources. For example, functions that retrieve sequences from GenBank require an internet connection, and running `MrBayes` from R requires a working local installation of `MrBayes`.
